/* Procedural Neural Audio Engine Simulator */
/* Generated by SYS_ARCH // 0x4B3A */

export const TRACKS = [
  { id: 0, title: "GEN_V1.0.1 // CORTEX_DECAY" },
  { id: 1, title: "SYS_ERR // FATAL_EXCEPTION" },
  { id: 2, title: "AI_NULL // ENDLESS_LOOP" }
];

class MachineSynth {
  private ctx: AudioContext | null = null;
  public isPlaying = false;
  public currentTrack = 0;
  
  private nextNoteTime = 0;
  private current8thNote = 0;
  private timerID: number | null = null;
  private lookahead = 25.0; // ms
  private scheduleAheadTime = 0.1; // s

  init() {
    if (!this.ctx) {
      this.ctx = new (window.AudioContext || (window as any).webkitAudioContext)();
    }
  }

  play(trackIndex: number) {
    this.init();
    this.currentTrack = trackIndex;
    if (!this.isPlaying) {
      this.isPlaying = true;
      this.ctx?.resume();
      this.current8thNote = 0;
      this.nextNoteTime = this.ctx!.currentTime + 0.05;
      this.scheduler();
    }
  }

  pause() {
    this.isPlaying = false;
    if (this.timerID) {
      clearTimeout(this.timerID);
      this.timerID = null;
    }
    this.ctx?.suspend();
  }

  nextNote() {
    const bpm = 140;
    const secondsPerBeat = 60.0 / bpm;
    this.nextNoteTime += 0.25 * secondsPerBeat;
    this.current8thNote++;
    if (this.current8thNote === 16) {
      this.current8thNote = 0;
    }
  }

  scheduleNote(beatNumber: number, time: number) {
    if (!this.ctx) return;
    const osc = this.ctx.createOscillator();
    const gainNode = this.ctx.createGain();
    
    osc.connect(gainNode);
    gainNode.connect(this.ctx.destination);

    let freq = 0;
    let type: OscillatorType = 'square';
    let baseVol = 0.05;

    // PROCEDURAL ALGORITHMS FOR AI DUMMY AUDIO
    if (this.currentTrack === 0) {
      type = 'square';
      const notes = [65.41, 0, 73.42, 65.41, 0, 98.00, 0, 65.41, 65.41, 0, 130.81, 0, 146.83, 0, 65.41, 0];
      freq = notes[beatNumber] || 0;
      baseVol = 0.04;
    } else if (this.currentTrack === 1) {
      type = 'sawtooth';
      const notes = [130.81, 146.83, 164.81, 130.81, 0, 0, 0, 0, 261.63, 0, 130.81, 0, 196.00, 0, 0, 0];
      freq = notes[beatNumber] || 0;
      if (Math.random() > 0.9) freq *= 2; // Glitch harmonic
      baseVol = 0.03;
    } else {
      type = 'triangle';
      freq = beatNumber % 4 === 0 ? 55.00 : 0;
      if (Math.random() > 0.8) {
        freq = 880.00; // random high glitch beep
        type = 'sine';
      }
      baseVol = 0.06;
    }

    if (freq === 0) return;

    osc.type = type;
    osc.frequency.value = freq;
    
    gainNode.gain.setValueAtTime(baseVol, time);
    gainNode.gain.exponentialRampToValueAtTime(0.001, time + 0.1);

    osc.start(time);
    osc.stop(time + 0.1);
  }

  scheduler = () => {
    while (this.nextNoteTime < this.ctx!.currentTime + this.scheduleAheadTime) {
      this.scheduleNote(this.current8thNote, this.nextNoteTime);
      this.nextNote();
    }
    if (this.isPlaying) {
      this.timerID = setTimeout(this.scheduler, this.lookahead) as unknown as number;
    }
  }
}

export const synthEngine = new MachineSynth();
